### ISSUE TITLE
A question about your SSNAu and SSNAo code

### ISSUE THREAD

**Issue by treenewbee0** [yiweizhang526/social-network-alignment#1]
I am a graduate student and just took my first step in scientific research focused on social network alignment. The SNNA model code you implemented helped me a lot. But I found that the code in both SNNAu and SNNAo directories seems to be the same. 
So could you please update the SNNAo code? I would be very appreciated if you can help me.

**Comment by yiweizhang526** [comment]
They are not the same.

**Comment by yiweizhang526** [comment]
> I am a graduate student and just took my first step in scientific research focused on social network alignment. The SNNA model code you implemented helped me a lot. But I found that the code in both SNNAu and SNNAo directories seems to be the same.
> So could you please update the SNNAo code? I would be very appreciated if you can help me.
They are not the same.

**Comment by UalwaysKnow** [comment]
They are not the same.
